# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used by the Gradle daemon.
# Increased heap size to prevent Jetifier/Gradle Java heap space errors.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m

# When configured, Gradle will run in incubating parallel mode.
# org.gradle.parallel=true

# AndroidX package structure
android.useAndroidX=true

# Enable Jetifier to migrate old Android Support Library dependencies
# (e.g. react-native-signature-capture) to AndroidX.
android.enableJetifier=true

# React Native architectures
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Enable React Native New Architecture
newArchEnabled=true

# Enable Hermes JS engine
hermesEnabled=true

# Enable/disable edge-to-edge display support
edgeToEdgeEnabled=false